language: node_js
node_js: "10"
cache: yarn
os: linux
dist: xenial

services:
  - xvfb

addons:
  chrome: "stable"
  firefox: "latest"

notifications:
  email:
    - player-web@g.globo

before_script: "npm run lint"

after_script: "cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage"
